[build]
  functions = "netlify/functions"  # your functions folder
  publish = "/"                     # your website root folder

[functions]
  node_bundler = "esbuild"          # recommended for modern JS

[build.environment]
  NODE_VERSION = "18"